:toc:
= Cobol Unit Test Tool DSL

== Introduction

The Cobol Unit Test Tool Domain Specific Language is designed to allow users to
easily generate Unit Tests at the paragraph level.  Its goal is to minimize the amount
of documentation the user is required to generate and maintain a test script.

== Program Level Fields

The following program level fields are required for a test file.

=== program-name

The name of the Cobol Program that you are creating tests for.

=== program-location

The PDS or Librarian directory containing the program.

==== copybook-location

The location or locations (comma separated) to get the copybooks from.

=== test-program-name

The Cobol Program name for the new test program that will be generated.  Cobol Program names can only
be 8 characters or less.

=== test-program-description

A description of the test program.

=== test-program-location

The PDS or Librarian location the test program will be stored.

=== test-jcl-location

The PDS or Librarian location the test JCL will be stored.

== Paragraph Level Fields

The following fields are available to create Unit test cases.

.Paragraph Level Fields
[cols="25%,10%,65%"]
|===
|Field | Required | Description
|*test-start*|Yes|Required to indicate the start of new test.
|*paragraph-name* | Yes | Original paragraph in the Cobol Program.
|*test-description |
|*test-end* |Yes | Required to indicate the end of a test.
|
===|

